"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from distutils.core import setup
import py2exe

OPTIONS = {
    'iconfile':'LDS.icns'
    }

setup(
    windows=[{
        'script':'invoiceStructuring.py',
        "icon_resources": [(1, "LDS.ico")]
        }]
)
